### ISSUE TITLE
[BUG] Mocha tests fail during release phase

### ISSUE THREAD

**Issue by adamretter** [eXist-db/documentation#875]
```
❯ mvn release:prepare
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< org.exist-db:exist-documentation >------------------
[INFO] Building eXist-db Documentation 6.1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-release-plugin:2.5.3:prepare (default-cli) @ exist-documentation ---
[INFO] Verifying that there are no local modifications...
[INFO]   ignoring changes on: **/pom.xml.releaseBackup, **/pom.xml.next, **/pom.xml.tag, **/pom.xml.branch, **/release.properties, **/pom.xml.backup
[INFO] Executing: /bin/sh -c cd /private/tmp/documentation && git rev-parse --show-toplevel
[INFO] Working directory: /private/tmp/documentation
[INFO] Executing: /bin/sh -c cd /private/tmp/documentation && git status --porcelain .
[INFO] Working directory: /private/tmp/documentation
[INFO] Checking dependencies and plugins for snapshots ...
What is the release version for "eXist-db Documentation"? (org.exist-db:exist-documentation) 6.1.0: :
What is SCM release tag or label for "eXist-db Documentation"? (org.exist-db:exist-documentation) 6.1.0: :
What is the new development version for "eXist-db Documentation"? (org.exist-db:exist-documentation) 6.1.1-SNAPSHOT: :
[INFO] Transforming 'eXist-db Documentation'...
[INFO] Not generating release POMs
[INFO] Executing goals 'clean verify'...
[INFO] Executing: /bin/sh -c cd /private/tmp/documentation && /usr/local/Cellar/maven/3.8.6/libexec/bin/mvn -s /var/folders/jp/8gqm072107l_rl1pvbw8rgjh0000gn/T/release-settings4006126854588397464.xml clean verify --no-plugin-updates -Psonatype-oss-release -P evolvedbinary-release
    [WARNING] Command line option -npu is deprecated and will be removed in future Maven versions.
    [INFO] Scanning for projects...
    [INFO]
    [INFO] ------------------< org.exist-db:exist-documentation >------------------
    [INFO] Building eXist-db Documentation 6.1.0
    [INFO] --------------------------------[ jar ]---------------------------------
    [INFO]
    [INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ exist-documentation ---
    [INFO]
    [INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ exist-documentation ---
    [INFO]
    [INFO] --- buildversion-plugin:1.0.3:set-properties (default) @ exist-documentation ---
    [INFO]
    [INFO] --- xml-maven-plugin:1.0.2:validate (default) @ exist-documentation ---
    [INFO]
    [INFO] --- ph-schematron-maven-plugin:6.3.3:validate (default) @ exist-documentation ---
    [INFO] Successfully parsed Schematron file '/private/tmp/documentation/src/main/schematron/docbook.sch'
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/xsl-transform/xsl-transform.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/xinclude/xinclude.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/incompatibilities/incompatibilities.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/contentextraction/contentextraction.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/configuration/configuration.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/documentation/documentation.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/oxygen/oxygen.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/xmldb/xmldb.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/docker/docker.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/lucene/lucene.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/getting-help/getting-help.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/datasync/datasync.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/devguide_rest/devguide_rest.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/production_web_proxying/production_web_proxying.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/xquery/xquery.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/xqsuite/xqsuite.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/security/security.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/devguide_xmldb/devguide_xmldb.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/triggers/triggers.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/exist-building/exist-building.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/jmx/jmx.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/http-request-session/http-request-session.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/faq_performance/faq_performance.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/author-reference/author-reference.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/devguide_manifesto/devguide_manifesto.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/xqdoc/xqdoc.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/scheduler/scheduler.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/development-starter/development-starter.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/using-collections/using-collections.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/troubleshooting/troubleshooting.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/templating/templating.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/integration-testing/integration-testing.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/devguide_indexes/devguide_indexes.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/ngram/ngram.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/extensions/extensions.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/dashboard/dashboard.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/testing/testing.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/devguide_log4j/devguide_log4j.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/uploading-files/uploading-files.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/properties/properties.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/java-admin-client/java-admin-client.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/fo-render/fo-render.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/urlrewrite/urlrewrite.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/kwic/kwic.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/deployment/deployment.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/tuning/tuning.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/webdav/webdav.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/devguide_soap/devguide_soap.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/oldrangeindex/oldrangeindex.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/upgrading/upgrading.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/update_ext/update_ext.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/xforms/xforms.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/indexing/indexing.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/devguide_codereview/devguide_codereview.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/getting-help-how-to-report/getting-help-how-to-report.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/versioning/versioning.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/devguide_xmlrpc/devguide_xmlrpc.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/backup/backup.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/legal/legal.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/newrangeindex/newrangeindex.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/learning-xquery/learning-xquery.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/repo/repo.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/beginners-guide-to-xrx-v4/beginners-guide-to-xrx-v4.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/basic-installation/basic-installation.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/validation/validation.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/advanced-installation/advanced-installation.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/production_good_practice/production_good_practice.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO] Validating XML file '/private/tmp/documentation/src/main/xar-resources/data/ant-tasks/ant-tasks.xml' against Schematron rules from '/private/tmp/documentation/src/main/schematron/docbook.sch' expecting success
    [INFO]
    [INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ exist-documentation ---
    [INFO] Using 'UTF-8' encoding to copy filtered resources.
    [INFO] Copying 613 resources
    [INFO] Copying 47 resources
    [INFO]
    [INFO] --- maven-compiler-plugin:3.10.0:compile (default-compile) @ exist-documentation ---
    [INFO] No sources to compile
    [INFO]
    [INFO] --- frontend-maven-plugin:1.12.1:install-node-and-npm (install node and npm) @ exist-documentation ---
    [INFO] Installing node version v14.17.6
    [INFO] Unpacking /Users/aretter/.m2/repository/com/github/eirslett/node/14.17.6/node-14.17.6-darwin-x64.tar.gz into /private/tmp/documentation/node/tmp
    [INFO] Copying node binary from /private/tmp/documentation/node/tmp/node-v14.17.6-darwin-x64/bin/node to /private/tmp/documentation/node/node
    [INFO] Installed node locally.
    [INFO] Installing npm version 7.24.0
    [INFO] Unpacking /Users/aretter/.m2/repository/com/github/eirslett/npm/7.24.0/npm-7.24.0.tar.gz into /private/tmp/documentation/node/node_modules
    [INFO] Installed npm locally.
    [INFO]
    [INFO] --- frontend-maven-plugin:1.12.1:npm (npm version bump) @ exist-documentation ---
    [INFO] Running 'npm version --no-git-tag-version --allow-same-version=true 6.1.0' in /private/tmp/documentation
    [INFO] v6.1.0
    [INFO]
    [INFO] --- frontend-maven-plugin:1.12.1:npm (npm install) @ exist-documentation ---
    [INFO] Running 'npm ci' in /private/tmp/documentation
    [INFO] npm WARN deprecated deep-assign@3.0.0: Check out `lodash.merge` or `merge-options` instead.
    [INFO] npm WARN deprecated flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
    [INFO] npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
    [INFO] npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
    [INFO] npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
    [INFO] npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
    [INFO] npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
    [INFO] npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
    [INFO] npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
    [INFO] npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
    [INFO] npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
    [INFO]
    [INFO] added 1334 packages, and audited 1335 packages in 11s
    [INFO]
    [INFO] 99 packages are looking for funding
    [INFO]   run `npm fund` for details
    [INFO]
    [INFO] 48 vulnerabilities (36 moderate, 9 high, 3 critical)
    [INFO]
    [INFO] To address issues that do not require attention, run:
    [INFO]   npm audit fix
    [INFO]
    [INFO] To address all issues possible (including breaking changes), run:
    [INFO]   npm audit fix --force
    [INFO]
    [INFO] Some issues need review, and may require choosing
    [INFO] a different dependency.
    [INFO]
    [INFO] Run `npm audit` for details.
    [INFO]
    [INFO] --- frontend-maven-plugin:1.12.1:gulp (gulp build) @ exist-documentation ---
    [INFO] Running 'gulp.js ' in /private/tmp/documentation
    [INFO] [00:39:24] Using gulpfile /private/tmp/documentation/gulpfile.js
    [INFO] [00:39:24] Starting 'default'...
    [INFO] [00:39:24] Starting 'cleanDist'...
    [INFO] [00:39:24] Finished 'cleanDist' after 7.73 ms
    [INFO] [00:39:24] Starting 'vendorFiles'...
    [INFO] [00:39:24] Finished 'vendorFiles' after 15 ms
    [INFO] [00:39:24] Starting 'buildScripts'...
    [INFO] [00:39:24] Starting 'lintScripts'...
    [INFO] [00:39:24] Starting 'buildStyles'...
    [INFO] [00:39:24] Starting 'buildSVGs'...
    [INFO] [00:39:24] Starting 'copyFiles'...
    [INFO] [00:39:24] Starting 'buildPack'...
    [INFO] [00:39:24] Starting 'prettyXml'...
    [INFO] [00:39:24] Finished 'buildScripts' after 2.85 ms
    [INFO] [00:39:24] Finished 'lintScripts' after 4.3 ms
    [INFO] [00:39:24] Finished 'buildStyles' after 11 ms
    [INFO] [00:39:24] Finished 'buildSVGs' after 12 ms
    [INFO] [00:39:24] Finished 'copyFiles' after 14 ms
    [INFO] [00:39:24] Finished 'buildPack' after 14 ms
    [INFO] [00:39:24] Finished 'prettyXml' after 17 ms
    [INFO] [00:39:24] Finished 'default' after 47 ms
    [INFO] Standard linter results: ✔ All OK!
    [INFO]
    [INFO]   Replace Autoprefixer browsers option to Browserslist config.
    [INFO]   Use browserslist key in package.json or .browserslistrc file.
    [INFO]
    [INFO]   Using browsers option can cause errors. Browserslist config can
    [INFO]   be used for Babel, Autoprefixer, postcss-normalize and other tools.
    [INFO]
    [INFO]   If you really need to use option, rename it to overrideBrowserslist.
    [INFO]
    [INFO]   Learn more at:
    [INFO]   https://github.com/browserslist/browserslist#readme
    [INFO]   https://twitter.com/browserslist
    [INFO]
    [INFO]
    [INFO] Browserslist: caniuse-lite is outdated. Please run:
    [INFO]   npx browserslist@latest --update-db
    [INFO]   Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
    [INFO]
    [INFO]   Replace Autoprefixer browsers option to Browserslist config.
    [INFO]   Use browserslist key in package.json or .browserslistrc file.
    [INFO]
    [INFO]   Using browsers option can cause errors. Browserslist config can
    [INFO]   be used for Babel, Autoprefixer, postcss-normalize and other tools.
    [INFO]
    [INFO]   If you really need to use option, rename it to overrideBrowserslist.
    [INFO]
    [INFO]   Learn more at:
    [INFO]   https://github.com/browserslist/browserslist#readme
    [INFO]   https://twitter.com/browserslist
    [INFO]
    [INFO]
    [INFO]
    [INFO]   Replace Autoprefixer browsers option to Browserslist config.
    [INFO]   Use browserslist key in package.json or .browserslistrc file.
    [INFO]
    [INFO]   Using browsers option can cause errors. Browserslist config can
    [INFO]   be used for Babel, Autoprefixer, postcss-normalize and other tools.
    [INFO]
    [INFO]   If you really need to use option, rename it to overrideBrowserslist.
    [INFO]
    [INFO]   Learn more at:
    [INFO]   https://github.com/browserslist/browserslist#readme
    [INFO]   https://twitter.com/browserslist
    [INFO]
    [INFO]
    [INFO]
    [INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ exist-documentation ---
    [INFO] Using 'UTF-8' encoding to copy filtered resources.
    [INFO] skip non existing resourceDirectory /private/tmp/documentation/src/test/resources
    [INFO]
    [INFO] --- maven-compiler-plugin:3.10.0:testCompile (default-testCompile) @ exist-documentation ---
    [INFO] No sources to compile
    [INFO]
    [INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ exist-documentation ---
    [INFO] No tests to run.
    [INFO]
    [INFO] --- maven-jar-plugin:3.2.2:jar (default-jar) @ exist-documentation ---
    [INFO] Building jar: /private/tmp/documentation/target/exist-documentation-6.1.0.jar
    [INFO]
    [INFO] --- maven-javadoc-plugin:2.7:jar (attach-javadocs) @ exist-documentation ---
    [INFO]
    [INFO] --- kuberam-expath-plugin:0.6.3:make-xar (create-xar) @ exist-documentation ---
    [INFO] outputDirectoryPath = /private/tmp/documentation/target
    [INFO] descriptorsDirectoryPath: /private/tmp/documentation/target/expath-descriptors
    [INFO] Using 'UTF-8' encoding to copy filtered resources.
    [INFO] Copying 1 resource to /private/tmp/documentation/target/make-xar-tmp
    [INFO] Using 'UTF-8' encoding to copy filtered resources.
    [INFO] Copying 1 resource to /private/tmp/documentation/target/expath-descriptors
    [INFO] Building zip: /private/tmp/documentation/target/exist-documentation-6.1.0.xar
    [INFO]
    [INFO] --- copy-rename-maven-plugin:1.0:copy (prepare-autodeploy) @ exist-documentation ---
    [INFO] Copied /private/tmp/documentation/target/exist-documentation-6.1.0.xar to /private/tmp/documentation/target/autodeploy/exist-documentation-6.1.0.xar
    [INFO]
    [INFO] --- public-xar-repo-plugin:1.2.0:resolve (prepare-autodeploy-deps) @ exist-documentation ---
    [INFO] Attempting to resolve package: {"abbrev": "templating", "version": "1.1.0"}
    [INFO]
    [INFO] Resolved package from cache: templating-1.1.0.xar
    [INFO]
    [INFO] --- docker-maven-plugin:0.40.2:start (docker-it-start) @ exist-documentation ---
    [INFO] DOCKER> [existdb/existdb:latest] "existdb-docs-tests": Start container 530be572c666
    [INFO] DOCKER> Pattern 'Server has started, listening on' matched for container 530be572c666
    [INFO] DOCKER> [existdb/existdb:latest] "existdb-docs-tests": Waited on log out 'Server has started, listening on' 7767 ms
    [INFO]
    [INFO] --- frontend-maven-plugin:1.12.1:npm (mocha tests) @ exist-documentation ---
    [INFO] Running 'npm test' in /private/tmp/documentation
    [INFO]
    [INFO] > exist-documentation@6.1.0 test
    [INFO] > mocha src/test/mocha/ --recursive --exit
    [INFO]
    [INFO]
    [INFO]
    [INFO]   running XQsuite test …
    [INFO] response body: {"servlet":"EXistServlet","message":"Document /db/apps/doc/modules/test-runner.xql not found","url":"/exist/rest/db/apps/doc/modules/test-runner.xql","status":"404"}
    [INFO]     1) returns 0 errors or failures
    [INFO]
    [INFO]
    [INFO]   0 passing (454ms)
    [INFO]   1 failing
    [INFO]
    [INFO]   1) running XQsuite test …
    [INFO]        returns 0 errors or failures:
    [INFO]      Error: expected 200 "OK", got 404 "Not Found"
    [INFO]       at Context.<anonymous> (src/test/mocha/xqSuite.js:16:8)
    [INFO]       at processImmediate (internal/timers.js:464:21)
    [INFO]   ----
    [INFO]       at Test._assertStatus (node_modules/supertest/lib/test.js:252:14)
    [INFO]       at /private/tmp/documentation/node_modules/supertest/lib/test.js:308:13
    [INFO]       at Test._assertFunction (node_modules/supertest/lib/test.js:285:13)
    [INFO]       at Test.assert (node_modules/supertest/lib/test.js:164:23)
    [INFO]       at localAssert (node_modules/supertest/lib/test.js:120:14)
    [INFO]       at /private/tmp/documentation/node_modules/supertest/lib/test.js:125:7
    [INFO]       at Test.Request.callback (node_modules/superagent/lib/node/index.js:866:3)
    [INFO]       at /private/tmp/documentation/node_modules/superagent/lib/node/index.js:1057:18
    [INFO]       at IncomingMessage.<anonymous> (node_modules/superagent/lib/node/parsers/json.js:21:7)
    [INFO]       at endReadableNT (internal/streams/readable.js:1317:12)
    [INFO]       at processTicksAndRejections (internal/process/task_queues.js:82:21)
    [INFO]
    [INFO]
    [INFO]
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time:  51.235 s
    [INFO] Finished at: 2023-01-04T00:39:48+01:00
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:npm (mocha tests) on project exist-documentation: Failed to run task: 'npm test' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
    [ERROR]
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR]
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  56.370 s
[INFO] Finished at: 2023-01-04T00:39:48+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.3:prepare (default-cli) on project exist-documentation: Maven execution failed, exit code: '1' -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by adamretter** [comment]
Could this be the chicken and egg problem? i.e. this is setup for eXist-db 6.1.0, but it needs to be released before eXist-db 6.1.0?

**Comment by adamretter** [comment]
The only mechanism for performing a release at this time is to skip the tests (after being certain that everything is working well), i.e.:

```bash
mvn release:prepare -Darguments="-DskipTests"
mvn release:perform -Darguments="-DskipTests"
```
