### ISSUE TITLE
Cypress tests are failing locally and in CI

### ISSUE THREAD

**Issue by adamretter** [eXist-db/documentation#903]
Java version 8, and Node.js version v14.17.4, on macOS Ventura.

```
❯ npm run cypress

> exist-documentation@6.1.1-SNAPSHOT cypress
> cypress run


====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        9.6.1                                                                          │
  │ Browser:        Electron 94 (headless)                                                         │
  │ Node Version:   v14.17.4 (/Users/aretter/.nvm/versions/node/v14.17.4/bin/node)                 │
  │ Specs:          2 found (diagnostic_spec.js, documentation_spec.js)                            │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────

  Running:  diagnostic_spec.js                                                              (1 of 2)
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating


  Diagnostics
    - should not find dead links


  0 passing (25ms)
  1 pending


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        1                                                                                │
  │ Passing:      0                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      1                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     0 seconds                                                                        │
  │ Spec Ran:     diagnostic_spec.js                                                               │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Video)

  -  Started processing:  Compressing to 32 CRF
  -  Finished processing: /Users/aretter/code/exist-documentation/src/test/cypress/vi    (0 seconds)
                          deos/diagnostic_spec.js.mp4


────────────────────────────────────────────────────────────────────────────────────────────────────

  Running:  documentation_spec.js                                                           (2 of 2)


  Documentation
    landing article
      1) "before each" hook for "should have content prose"


  0 passing (682ms)
  1 failing

  1) Documentation
       landing article
         "before each" hook for "should have content prose":
     CypressError: `cy.visit()` failed trying to load:

http://localhost:8080/exist/apps/doc/

The response we received from your web server was:

  > 500: Internal Server Error

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Documentation`
      at http://localhost:8080/__cypress/runner/cypress_runner.js:163581:84
      at visitFailedByErr (http://localhost:8080/__cypress/runner/cypress_runner.js:162902:12)
      at http://localhost:8080/__cypress/runner/cypress_runner.js:163561:13
      at tryCatcher (http://localhost:8080/__cypress/runner/cypress_runner.js:13022:23)
      at Promise._settlePromiseFromHandler (http://localhost:8080/__cypress/runner/cypress_runner.js:10957:31)
      at Promise._settlePromise (http://localhost:8080/__cypress/runner/cypress_runner.js:11014:18)
      at Promise._settlePromise0 (http://localhost:8080/__cypress/runner/cypress_runner.js:11059:10)
      at Promise._settlePromises (http://localhost:8080/__cypress/runner/cypress_runner.js:11135:18)
      at _drainQueueStep (http://localhost:8080/__cypress/runner/cypress_runner.js:7729:12)
      at _drainQueue (http://localhost:8080/__cypress/runner/cypress_runner.js:7722:9)
      at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:8080/__cypress/runner/cypress_runner.js:7738:5)
      at Async.drainQueues (http://localhost:8080/__cypress/runner/cypress_runner.js:7608:14)
  From Your Spec Code:
      at Context.eval (http://localhost:8080/__cypress/tests?p=src/test/cypress/integration/documentation_spec.js:103:8)




  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        6                                                                                │
  │ Passing:      0                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      5                                                                                │
  │ Screenshots:  1                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     0 seconds                                                                        │
  │ Spec Ran:     documentation_spec.js                                                            │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Screenshots)

  -  /Users/aretter/code/exist-documentation/src/test/cypress/screenshots/documentati     (1280x720)
     on_spec.js/Documentation -- should have content prose -- before each hook (faile
     d).png


  (Video)

  -  Started processing:  Compressing to 32 CRF
  -  Finished processing: /Users/aretter/code/exist-documentation/src/test/cypress/vi    (0 seconds)
                          deos/documentation_spec.js.mp4


====================================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  diagnostic_spec.js                        24ms        1        -        -        1        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  documentation_spec.js                    676ms        6        -        1        -        5 │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  1 of 2 failed (50%)                      700ms        7        -        1        1        5
```

**Comment by adamretter** [comment]
This is caused by a compatibility issue with eXist-db 7.x.x due to invalid XQuery that was previously accepted in older versions of eXist-db. The HTTP 500 error reported from eXist-db is:

```
GET /exist/apps/doc/ HTTP/1.1
Connection: keep-alive
accept: text/html,*/*
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/9.6.1 Chrome/94.0.4606.81 Electron/15.5.1 Safari/537.36
host: localhost:8080

HTTP/1.1 500 Server Error
Content-Type: application/xml;charset=utf-8
Transfer-Encoding: chunked
Server: Jetty(11.0.14)

<?xml version="1.0" ?><exception><path>/db/apps/doc/modules/view.xql</path><message>err:XPTY0004 xs:integer(2) is not a sub-type of xs:int [at line 299, column 34, source: /db/apps/doc/modules/view.xql]
In function:
	(xs:string, xs:int) [20:24:/db/apps/doc/modules/view.xql]
	templates:resolve(xs:integer, xs:string, function(*)) [294:5:/home/ubuntu/exist-7.0.0-SNAPSHOT/exist-distribution/target/exist-distribution-7.0.0-SNAPSHOT-dir/etc/../data/expathrepo/templating-1.1.0/content/templates.xqm]
	templates:resolve(xs:string, function(*)) [187:18:/home/ubuntu/exist-7.0.0-SNAPSHOT/exist-distribution/target/exist-distribution-7.0.0-SNAPSHOT-dir/etc/../data/expathrepo/templating-1.1.0/content/templates.xqm]
	templates:call(item(), element(), map(*)) [137:36:/home/ubuntu/exist-7.0.0-SNAPSHOT/exist-distribution/target/exist-distribution-7.0.0-SNAPSHOT-dir/etc/../data/expathrepo/templating-1.1.0/content/templates.xqm]
	templates:process(node()*, map(*)) [133:51:/home/ubuntu/exist-7.0.0-SNAPSHOT/exist-distribution/target/exist-distribution-7.0.0-SNAPSHOT-dir/etc/../data/expathrepo/templating-1.1.0/content/templates.xqm]
	templates:process(node()*, map(*)) [90:9:/home/ubuntu/exist-7.0.0-SNAPSHOT/exist-distribution/target/exist-distribution-7.0.0-SNAPSHOT-dir/etc/../data/expathrepo/templating-1.1.0/content/templates.xqm]
	templates:apply(node()+, function(*), map(*)?, map(*)?) [29:5:/home/ubuntu/exist-7.0.0-SNAPSHOT/exist-distribution/target/exist-distribution-7.0.0-SNAPSHOT-dir/etc/../data/expathrepo/templating-1.1.0/content/templates.xqm]</message></exception>
```
